name: Build and Release APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Create keystore from secrets
      run: |
        echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/senvia-release-key.jks
        if [ ! -f app/senvia-release-key.jks ] || [ ! -s app/senvia-release-key.jks ]; then
          echo "Error: Keystore file not created or is empty"
          echo "Base64 length: ${#KEYSTORE_BASE64}"
          exit 1
        fi
        echo "Keystore created successfully"
        ls -la app/senvia-release-key.jks
      env:
        KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

    - name: Make gradlew executable
      run: chmod +x ./gradlew

    - name: Build Release APK
      env:
        KEYSTORE_FILE: senvia-release-key.jks
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      run: ./gradlew assembleRelease

    - name: Get version info
      id: version
      run: |
        VERSION=$(grep "versionName" app/build.gradle.kts | cut -d'"' -f2)
        VERSION_CODE=$(grep "versionCode" app/build.gradle.kts | grep -o '[0-9]\+')
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "version_code=$VERSION_CODE" >> $GITHUB_OUTPUT

    - name: Rename APK
      run: |
        mv app/build/outputs/apk/release/app-release.apk senvia-v${{ steps.version.outputs.version }}.apk

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: senvia-v${{ steps.version.outputs.version }}
        path: senvia-v${{ steps.version.outputs.version }}.apk

    - name: Create GitHub Release
      if: startsWith(github.ref, 'refs/tags/v')
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.ref_name }}
        name: ${{ github.ref_name }}
        body: |
          **Requirements:** Android 8.0+ (API 26+)
          
          See [README](https://github.com/${{ github.repository }}/blob/main/README.md) for setup instructions
        draft: false
        prerelease: false
        files: |
          senvia-v${{ steps.version.outputs.version }}.apk
        generate_release_notes: true